// Vue/src/App.vue
<template>
  <div id="app_main">
    <template v-if="!loading">
      <main class="animate__animated animate__zoomIn"
        :style="{backgroundImage:`
          linear-gradient(180deg, rgba(0, 0, 0, 0.6) 0%,
          rgba(0, 0, 0, 0) 100%), url(${bg_img})
        `}"
      >
        <!-- Settings Modal -->
        <SettingsComp
          v-if="settings.open"
          :settings="settings"
          :toggle_settings="toggle_settings"
          :update_settings="update_settings"
        />
        <!-- Main Content Starts Here -->
        <CurrentTemp
          :toggle_settings="toggle_settings"
          :curr_temp="curr_temp"
          :title="title"
          :location="location"
          :temp_unit="settings.temp"
        />
        <CurrOthMtx
          :curr_other_metrics="curr_other_metrics"
          :temp_unit="settings.temp"
          :dist_unit="settings.dist"
          :measure_unit="settings.measure"
        />
        <Forcast
          :req_url="req_url"
          :forcast_day="forcast_day"
          :temp_unit="settings.temp"
        />
        <TimeReload
          :loading="loading"
        />
      </main>
      <footer class='footer animate__animated animate__fadeInUp'>
        <p>Made With <i class="fa-solid fa-heart"></i> By <a target="_blank" href="https://github.com/Aditya-Invento/">Aditya Burmam</a></p>
      </footer>
    </template>
    <Loader v-else />
  </div>
</template>

<script>
// Components
import CurrentTemp from './components/CurrentTemp.vue';
import CurrOthMtx from './components/CurrOthMtx/CurrOthMtx.vue';
import Forcast from './components/Forcast/Forcast.vue';
import TimeReload from './components/TimeReload.vue';
import SettingsComp from './components/Modal/Settings.vue';
import Loader from './components/Loader.vue';
// Default Data
import Def_Data from './utils/default_data';

// Setting Options
export default {
  name: 'App',
  components: {Loader,CurrentTemp,CurrOthMtx,Forcast,TimeReload,SettingsComp},
  data() {return {...Def_Data}},
  methods: {
    update_settings(what,to) {
      const can_update = {
        open:1,//true / false
        country_code: 1,//NA / <num>
        temp: 1,//c / f
        dist: 1,//mph / kph
        measure: 1,//mm / inch
        search_by: 1// auto / city / zip
      }
      if(can_update[what]) this.settings = {...this.settings,[what]:to};
    },
    toggle_settings() {this.update_settings('open',!this.settings.open)}
  }
};
</script>

<style scoped>
  .footer {
    margin-top: 30px;
  }
  .footer > p {
    font-size: 20px;
    font-weight: 500;
  }
</style>

// React/src/App.jsx
import { WeatherStore } from './Context/Store';
import { useContext, useEffect, useState } from 'react';
import SettingsComp from './Components/SettingsComp';
import CurrTempComp from './Components/CurrTempComp';
import CurrOthMetxComp from './Components/CurrOthMetxComp';
import ForcastComp from './Components/ForcastComp';
import TimeReloadComp from './Components/TimeReloadComp';

import get_weather from '../Utils/api-services';

function App() {
  const [pageLoad,setPageLoad] = useState(false);
  const [refreshing,setRefreshing] = useState(false);
  const {state,setState} = useContext(WeatherStore);
  const {
    req_url,settings,bg_img,
    curr_temp,curr_other_metrics,
    forcast_day,alerts
  } = state;

  const update_settings = (what,to)=> {
    const can_update = {
      open:1,//true / false
      country_code: 1,//NA / <num>
      temp: 1,//c / f
      dist: 1,//mph / kph
      measure: 1,//mm / inch
      search_by: 1// auto / city / zip
    }
    if(can_update[what]) {
      setState(pre=>{
        return {...pre,settings:{...pre.settings,[what]:to}}
      });
    }
  }

  useEffect(()=>{
    if(!pageLoad) {
      get_weather({req_url,setState,setPageLoad});
    }
  },[pageLoad]);
  useEffect(()=>{
    const intervalId = setInterval(() => {
      get_weather({req_url,setState:setState,refresh:true,setRefreshing});
    }, 600000);
    return () => {
      clearInterval(intervalId);
    };
  },[]);


  return (
    <div id="app_main">
      {pageLoad ? <>
        <main style={{backgroundImage:`linear-gradient(180deg, rgba(0, 0, 0, 0.6) 0%, rgba(0, 0, 0, 0) 100%), url('${req_url}/bg_imgs/${bg_img}.png')`}} className="animate__animated animate__zoomIn">
          {settings.open && <SettingsComp toggle_settings={()=>update_settings('open',!settings.open)} update_settings={update_settings} settings={settings} />}
          <CurrTempComp
            temp_unit={settings.temp}
            curr_temp={curr_temp}
            toggle_settings={()=>update_settings('open',!settings.open)}
          />
          <CurrOthMetxComp
            temp_unit={settings.temp}
            dist_unit={settings.dist}
            measure_unit={settings.measure}
            curr_other_metrics={curr_other_metrics}
          />
          <ForcastComp
            req_url={req_url}
            temp_unit={settings.temp}
            forcast_day={forcast_day}
          />
          <TimeReloadComp refreshing={refreshing} refresh_api={()=>get_weather({req_url,setState:setState,refresh:true,setRefreshing})} />
        </main>
        <footer style={{marginTop:'30px'}} className='animate__animated animate__fadeInUp'>
          <p style={{fontSize:'20px',fontWeight:'600'}}>Made With <i className="fa-solid fa-heart"></i> By <a target="_blank" href="https://github.com/Aditya-Invento/">Aditya Burmam</a></p>
        </footer>
      </> : <div className='loader'>
          <div className="loading"></div>
          <p style={{fontSize:'20px',fontWeight:'600',marginTop:'30px',textAlign:'center'}}>Loading...</p>
        </div>}
    </div>
  )
}

export default App
